/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backend.inventorymanagementclient.GUI;

import backend.inventorymanagementclient.InventoryManagementClient;
import javax.swing.JOptionPane;

/**
 *
 * @author isabela
 */
public class Create extends javax.swing.JFrame {
   public VentanaPrincipal ventana;
    /**
     * Creates new form Create
     */
    public Create(VentanaPrincipal ventana) {
        this.ventana = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TnameProduct = new javax.swing.JTextField();
        BcreateProduct = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        Tprecio = new javax.swing.JTextField();
        Tcantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdescription = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nuevo producto");

        TnameProduct.setText("Nombre");
        TnameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameProductActionPerformed(evt);
            }
        });

        BcreateProduct.setText("Crear");
        BcreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcreateProductActionPerformed(evt);
            }
        });

        Bback.setText("Atras");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });

        Tprecio.setText("Precio");
        Tprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TprecioActionPerformed(evt);
            }
        });
        Tprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TprecioKeyTyped(evt);
            }
        });

        Tcantidad.setText("Cantidad");
        Tcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TcantidadKeyTyped(evt);
            }
        });

        Tdescription.setColumns(20);
        Tdescription.setRows(5);
        Tdescription.setText("Descripcion");
        jScrollPane1.setViewportView(Tdescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BcreateProduct)
                .addGap(18, 18, 18)
                .addComponent(Bback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TnameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(Tcantidad))
                        .addGap(149, 149, 149))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TnameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Tcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BcreateProduct)
                    .addComponent(Bback))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 277));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setVentana(VentanaPrincipal ventana){
        ventana.setVisible(true);
        this.setVisible(false);
    }
            
          
    private void TnameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameProductActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
       
    if (ventana != null) {
        ventana.setVisible(true);
        this.setVisible(false);
    } else {
        System.err.println("Error: ventana es null");
    }
        this.setVisible(false);
    }//GEN-LAST:event_BbackActionPerformed

    private void TprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TprecioActionPerformed

    private void TprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TprecioKeyTyped
        char key = evt.getKeyChar();
        if(Character.isLetter(key)){
            evt.consume();
        }
    }//GEN-LAST:event_TprecioKeyTyped

    private void TcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TcantidadKeyTyped
        char key = evt.getKeyChar();
        if(Character.isLetter(key)){
            evt.consume();
        }
    }//GEN-LAST:event_TcantidadKeyTyped

    private void BcreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcreateProductActionPerformed
String nombre = TnameProduct.getText().trim();
        String precioTexto = Tprecio.getText().trim();
        String cantidadTexto = Tcantidad.getText().trim();
        String descripcion = Tdescription.getText().trim();

        // Validaciones
        if (nombre.isEmpty() || precioTexto.isEmpty() || cantidadTexto.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int cantidad = Integer.parseInt(cantidadTexto);
            float precio = Float.parseFloat(precioTexto);

            // Obtener el InventoryManagementClient desde la VentanaPrincipal
            InventoryManagementClient inventoryManagementClient = ventana.getManagementClient();

            // Llamar al método para agregar el producto a la base de datos
            String respuesta = inventoryManagementClient.addProductToDB(nombre, cantidad, precio, descripcion);

            // Mostrar la respuesta del servidor (en este caso, la simulación de la inserción)
            JOptionPane.showMessageDialog(this, respuesta, "Respuesta del Servidor", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad y precio deben ser valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.setVisible(false);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_BcreateProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton BcreateProduct;
    private javax.swing.JTextField Tcantidad;
    private javax.swing.JTextArea Tdescription;
    private javax.swing.JTextField TnameProduct;
    private javax.swing.JTextField Tprecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
