/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backend.inventorymanagementclient.GUI;

import backend.inventorymanagementclient.InventoryManagementClient;
import javax.swing.JOptionPane;

/**
 *
 * @author isabela
 */
public class Edit extends javax.swing.JFrame {
    public VentanaPrincipal ventana;
    String oldName;
    /**
     * Creates new form Edit
     */
    public Edit(String oldName) {
        this.oldName = oldName;
        initComponents();
    }
    
    public void setVentana(VentanaPrincipal ventana){
        this.ventana = ventana;
        ventana.setVisible(true);
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdescription = new javax.swing.JTextArea();
        Tname = new javax.swing.JTextField();
        Tprice = new javax.swing.JTextField();
        Tcantidad = new javax.swing.JTextField();
        Bedit = new javax.swing.JButton();
        Bback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 290));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Editar producto");

        Tdescription.setColumns(20);
        Tdescription.setRows(5);
        Tdescription.setText("Nueva descripcion");
        jScrollPane1.setViewportView(Tdescription);

        Tname.setText("Nuevo nombre");
        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });

        Tprice.setText("Nuevo precio");
        Tprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpriceActionPerformed(evt);
            }
        });
        Tprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TpriceKeyTyped(evt);
            }
        });

        Tcantidad.setText("Nueva cantidad");
        Tcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcantidadActionPerformed(evt);
            }
        });
        Tcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TcantidadKeyTyped(evt);
            }
        });

        Bedit.setText("Editar");
        Bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeditActionPerformed(evt);
            }
        });

        Bback.setText("Atras");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(Tname))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tprice)
                            .addComponent(Tcantidad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(Bedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bback))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tprice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Tcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bedit)
                    .addComponent(Bback))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameActionPerformed

    private void TpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpriceActionPerformed

    private void TcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcantidadActionPerformed

    private void BeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeditActionPerformed
       String newName = Tname.getText().trim();
       String newDescription = Tdescription.getText().trim();
       String newStockStr = Tcantidad.getText().trim();
       String newPriceStr = Tprice.getText().trim();

       // Validar los campos antes de enviar la solicitud
       if (newName.isEmpty() || newDescription.isEmpty() || newStockStr.isEmpty() || newPriceStr.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       }

       int newStock;
       float newPrice;
       try {
           newStock = Integer.parseInt(newStockStr);
           newPrice = Float.parseFloat(newPriceStr);
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Stock y precio deben ser valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       InventoryManagementClient client = new InventoryManagementClient();

       // Llamar a la función modifyProductNameInDB
       String response = client.modifyProductNameInDB(oldName, newName, newStock, newPrice, newDescription);

       // Mostrar mensaje de éxito o error
       if (response.startsWith("SUCCESS")) {
           JOptionPane.showMessageDialog(this, "Producto modificado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
       } else {
           JOptionPane.showMessageDialog(this, "Error al modificar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
       }
       ventana.setVisible(true);
        this.setVisible(false);         
                
    }//GEN-LAST:event_BeditActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BbackActionPerformed

    private void TpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpriceKeyTyped
        char key = evt.getKeyChar();
        if(Character.isLetter(key)){
            evt.consume();
        }
    }//GEN-LAST:event_TpriceKeyTyped

    private void TcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TcantidadKeyTyped
        char key = evt.getKeyChar();
        if(Character.isLetter(key)){
            evt.consume();
        }
    }//GEN-LAST:event_TcantidadKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Bedit;
    private javax.swing.JTextField Tcantidad;
    private javax.swing.JTextArea Tdescription;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
